monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: debug
      handler: nested
      buffer_size: 200
      # Ne mets pas excluded_http_codes ici: il est déjà défini ailleurs (config/packages/monolog.yaml)

    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      formatter: monolog.formatter.json
